### ISSUE TITLE
Curious to better understand search.value and this.search

### ISSUE THREAD

**Issue by jimmique-parsons** [Sage911/blog-autocomplete#1]
Hello Stefan, I was researching how to do do suggestions for a music search bar and I came across your post on Medium, I am trying to convert the component from a class to functional component, however, I'm stumped by the " this.search.value," as well as "this.search". Would you mind (if you can) explaining how I would change this to utilize it in a class component? This is what I got so far. 

`const { API_KEY } = process.env;
const API_URL = 'http://api.musicgraph.com/api/v2/artist/suggest';

const Search = () => {
  
  const [state, setState] = useState({
    query: '',
    results: [],
  });
  const getInfo = () => {
    axios
      .get(`${API_URL}?api_key=${API_KEY}&prefix=${state.query}&limit=7`)
      .then(({ data }) => {
        setState((prevState) => ({
          ...prevState, 
          results: data.data,
        }));
      });
  };
  const handleInputChange = () => {
    setState(
      (prevState) => ({
        ...prevstate, 
        query: this.search.value, //**would I need a variable for search in a functional component?**
      }),
      () => {
        if (state.query && state.query.length > 1) {
          if (state.query.length % 2 === 0) {
            getInfo();
          }
        } else if (!state.query) {
        }
      }
    );
  };

  return (
    <form>
      <input
        placeholder='Search for...'
        ref={(input) => (this.search = input)} /* **No idea how to input 'search' for a functional component, would I need to create a variable for this?**  */
        onChange={() => handleInputChange()} 
      />
      <Suggestions results={state.results} />
    </form>
  );
};
export default Search;`

**Comment by saaage** [comment]
Hey Jimmique, glad you found my post (I've been meaning to write an updated version using a functional component). 

You're off to a good start replacing the class component `state` with the `useState` hook. We can break up the state here into two parts, one for `query` and one for `results` to make things easier to reason about.

```js
const [query, setQuery] = useState("")

const [results, setResults] = useState([])
```

In the post, `this.search` is  a property on the (class) component that is being set using the function was passed to the `ref` prop on `input`. We then used`this.search` to get the current value of what is in the input (`this.search.value`). There is a simpler way to get the value (using the event), which is the way I would go now if I were to write it again. But if you're still interested in the functional component version of refs check out the [useRef docs](https://reactjs.org/docs/hooks-reference.html#useref).

To use the event, pass a function the `input`'s `onChange` prop that looks something like:

```js
const handleChange = event => doSomethingWith(event.target.value)
```

The last piece of this is to decide _how_ to fetch the data when the query is at a certain length, which is what this bit of code was doing:

 (replace `this.state.query` with `query` and `this.getInfo` with `getInfo`)
```js
() => {
  if (this.state.query && this.state.query.length > 1) {
    if (this.state.query.length % 2 === 0) {
      this.getInfo()
    }
 } 
```

The API for running an effect is different using functional components, you'll need to reach for the `useEffect` hook here. 

I've put together a [codesandbox](https://codesandbox.io/s/blog-autocomplete-hooks-1sfcx) with one solution, in case you want to check it out. I faked the `axios` data, but it should work the same. Let me know if you have more questions.

**Comment by jimmique-parsons** [comment]
Thank you for the reply, that makes sense. Ok I've ran into another issue (maybe you can help me with as well). So now I am trying to swap the api to (https://developers.deezer.com/api/search/history) while using your solution, it does not require an API key so I commented that out. But now I have ran into an error that states   

**TypeError
Cannot read property 'map' of undefined**
_Search
/src/AutoComplete.js:31:17_
```
  28 | <input placeholder="Search for..." onChange={handleInputChange} />
  29 | 
  30 | <ul>
> 31 |   {results.map(r => (
     |           ^
  32 |     <li key={r.name}>{r.name}</li>
  33 |   ))}
  34 | </ul>

```

This is the sample code...

**Autocomplete.js**
```

import React, { useState, useEffect } from "react"
import { axiosWithAuth } from "./axiosWithAuth"

//const { API_KEY } = process.env

const API_URL = "/search/history"

const Search = () => {
  const [query, setQuery] = useState("")

  const [results, setResults] = useState([])

  const getInfo = () =>
    axiosWithAuth()
      .get(`${API_URL}?&prefix=${query}&limit=7`)
      .then(({ data }) => setResults(data.data))

  useEffect(() => {
    if (query.length > 1 && query.length % 2 === 0) getInfo()
  })

  const handleInputChange = event => {
    setQuery(event.target.value)
  }

  return (
    <>
      <input placeholder="Search for..." onChange={handleInputChange} />

      <ul>
        {results.map(r => (
          <li key={r.name}>{r.name}</li>
        ))}
      </ul>
    </>
  )
}

export default Search

```

**axiosWithAuth.js**
```
import axios from "axios"

export const axiosWithAuth = () => {
  const token = localStorage.getItem("token")

  return axios.create({
    headers: {
      "Content-Type": "application/json",
      Authorization: `${token}`
    },
    baseURL: "https://api.deezer.com"
  })
}

```

**Comment by saaage** [comment]
I would check the shape of response, I'm guessing the API doesn't wrap its' results in a top level `data` key, so `data.data` may be undefined.

**Comment by jimmique-parsons** [comment]
I will give it a shot, thank you for all the help Stefan!
